site_name: Documentação Virgo

nav:
  - Página Inicial: index.md
  - Documento de Visão:
      - Visão do Produto: "documento-visao/visao-geral-produto.md"
      - Visão Geral do Projeto: "documento-visao/visao-geral-projeto.md"
      - Processo de Desenvolvimento de Software: "documento-visao/processo-dev-software.md"
      - Declaração de Escopo do Projeto: "documento-visao/declaração-escopo-projeto.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documento de Plano de Testes: "documento-plano-testes/documento-plano-testes.md"
  - Atas de reuniao:
      - Cliente:
          - Ata 1: "atas-reuniao/cliente/ata-reuniao-1.md"
          - Ata 2: "atas-reuniao/cliente/ata-reuniao-2.md"
          - Ata 3: "atas-reuniao/cliente/ata-reuniao-3.md"
          - Ata 4: "atas-reuniao/cliente/ata-reuniao-4.md"
          - Ata 5: "atas-reuniao/cliente/ata-reuniao-5.md"
          - Ata 6: "atas-reuniao/cliente/ata-reuniao-6.md"
          - Ata 7: "atas-reuniao/cliente/ata-reuniao-7.md"

      - Equipe:
          - Ata 1: "atas-reuniao/equipe/ata-reuniao-1-equipe.md"
          - Ata 2: "atas-reuniao/equipe/ata-reuniao-2-equipe.md"
          - Ata 3: "atas-reuniao/equipe/ata-reuniao-3-equipe.md"
          - Ata 4: "atas-reuniao/equipe/ata-reuniao-4-equipe.md"
          - Ata 5: "atas-reuniao/equipe/ata-reuniao-5-equipe.md"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: green
      accent: green
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: green
      accent: green

markdown_extensions:
  - attr_list

extra_css:
  - css/custom.css
