site_name: Documentação Virgo

nav:
  - Página Inicial: index.md

  - Atas de reuniao:
      - Cliente:
          - Ata 1: "atas-reuniao/cliente/ata-reuniao-1.md"
          - Ata 2: "atas-reuniao/cliente/ata-reuniao-2.md"
          - Ata 3: "atas-reuniao/cliente/ata-reuniao-3.md"
      - Equipe:
          - Ata 1: "atas-reuniao/equipe/ata-reuniao-1-equipe.md"

  - Documento de Visão: "documento-visao/documento-visao.md"
  - Documento de Requisitos: "documento-requisitos/documento-requisitos.md"
  - Documento de Arquitetura: "documento-arquitetura/documento-arquitetura.md"
  - Documento de Plano de Testes: "documento-plano-testes/documento-plano-testes.md"

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: green
      accent: green
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: green
      accent: green
